wp post create --post_title="Josh and Britta" --post_status=publish
wp post create --post_title="Garrett and Jenna" --post_status=publish
wp post create --post_title="Andy and Sara" --post_status=publish
wp post create --post_title="Dan and Andrea" --post_status=publish
wp post create --post_title="Justin and Steph" --post_status=publish
wp post create --post_title="Anthony and Laura" --post_status=publish
wp post create --post_title="Thomas and Kathryn" --post_status=publish
wp post create --post_title="David and Jane" --post_status=publish
wp post create --post_title="Spencer and Melissa" --post_status=publish
wp post create --post_title="Noah and Stephanie" --post_status=publish
wp post create --post_title="Grant and Keely" --post_status=publish
wp post create --post_title="Collin and Christy" --post_status=publish
wp post create --post_title="Luke and Ariel" --post_status=publish
wp post create --post_title="Theo and Hannah" --post_status=publish
wp post create --post_title="Jason and Sarah" --post_status=publish
wp post create --post_title="Dan and Alex" --post_status=publish
wp post create --post_title="Sean and Natalie" --post_status=publish
wp post create --post_title="Kevin and Sarah" --post_status=publish
wp post create --post_title="Joe and Laura" --post_status=publish
wp post create --post_title="Brad and Nicole" --post_status=publish
wp post create --post_title="Jeff and Lacy" --post_status=publish
wp post create --post_title="Vince and Anna" --post_status=publish
wp post create --post_title="Kurt and Laura" --post_status=publish
wp post create --post_title="Mike and Liana" --post_status=publish
wp post create --post_title="Sam and Julie" --post_status=publish
wp post create --post_title="Johnny and Samantha" --post_status=publish
wp post create --post_title="Joe and Stephanie" --post_status=publish
wp post create --post_title="Cody and Jess" --post_status=publish
wp post create --post_title="Matt and Anna" --post_status=publish
wp post create --post_title="Max and Samantha" --post_status=publish
wp post create --post_title="John and Amy" --post_status=publish
wp post create --post_title="Jonathan and Danica" --post_status=publish
wp post create --post_title="Ryan and Lauryn" --post_status=publish
wp post create --post_title="Rob and Sarah" --post_status=publish
wp post create --post_title="Chris and Lindsay" --post_status=publish
wp post create --post_title="Mark and Madison" --post_status=publish
wp post create --post_title="David and Anne" --post_status=publish
wp post create --post_title="Joseph and Aly" --post_status=publish
wp post create --post_title="Jason and Heather" --post_status=publish
wp post create --post_title="Mike and Jess" --post_status=publish
wp post create --post_title="2016 Engagements" --post_status=publish
wp post create --post_title="Robbie and Rachel" --post_status=publish
wp post create --post_title="Rusty and Kaitlin" --post_status=publish
wp post create --post_title="Aaron and Lynda" --post_status=publish
wp post create --post_title="Seth and Stephanie" --post_status=publish
wp post create --post_title="Seth and Haley" --post_status=publish
wp post create --post_title="Tim and Christina" --post_status=publish
wp post create --post_title="Charles and Genevieve" --post_status=publish
wp post create --post_title="Jerry and Lara" --post_status=publish
wp post create --post_title="Matt and Ally" --post_status=publish
wp post create --post_title="Adnan and Christina" --post_status=publish
wp post create --post_title="Corey and Caren" --post_status=publish
wp post create --post_title="Mike and Jamie" --post_status=publish
wp post create --post_title="Kevin and Mariko" --post_status=publish
wp post create --post_title="Christian and ThuyLinh" --post_status=publish
wp post create --post_title="Layne and Lauren" --post_status=publish
wp post create --post_title="Tyler and Emily" --post_status=publish
wp post create --post_title="Ken and Liz" --post_status=publish